### ISSUE TITLE
(zed noob) Indentation?

### ISSUE THREAD

**Issue by machinemob** [jackTabsCode/zed-just#16]
Is there any reason why this extension wouldn't indent (new or existing justfile) at all? My expectation is that it would indent automatically after a task name and the successive lines of a "recipe" (?)

eg. 

```
mytask:
    my command this should indent
    another command this should indent
    ....
```

Macos Sonoma (14.4.1 (23E224))
Zed (homebrew) 0.164.2
Justfile extension: 0.1.3
Just: 1.36.0

Thanks for reading!

**Comment by jackTabsCode** [comment]
This extension doesn't provide a formatter.
