### ISSUE TITLE
Support for `Justfile` (starting with a capitalized `J`

### ISSUE THREAD

**Issue by lyssieth** [jackTabsCode/zed-just#6]
Or ideally any case combination, but I don't know if that's possible.

Out of some kind of habit, I always name my justfiles `Justfile`, and thus this extension sadly can't detect them.

**Comment by jackTabsCode** [comment]
This should already be supported

**Comment by lyssieth** [comment]
It doesn't seem to be, at least with what's currently installed. I'm on `0.143.7`, with the extension @ 0.1.0, so if 0.1.1 gets pushed and does fix it I'll let you know.

On Linux, but that shouldn't be relevant.

![An image of a censored `Justfile`, with no syntax highlighting. In the bottom right, it says `Unknown` instead of the expected language](https://github.com/user-attachments/assets/ce8bed8a-fa09-411b-9e77-59ae904d7ab1)

**Comment by jackTabsCode** [comment]
https://github.com/zed-industries/extensions/pull/1009

**Comment by jackTabsCode** [comment]
https://github.com/zed-industries/extensions/pull/1009
